app:
    resource: '@AppBundle/Controller/'
    type: annotation

public_routes:
    resource: "@BoabCmsBundle/Resources/config/routing/public.xml"

user_api:
    resource: "@UserBundle/Resources/config/api/routes.xml"
    prefix:   /{_api}
    requirements:
        _api: api|rest
user_admin:
    resource: "@UserBundle/Resources/config/routing/admin.xml"
user_account:
    resource: "@UserBundle/Resources/config/routing/account.xml"

admin_routes:
    resource: "@BoabCmsBundle/Resources/config/routing/admin.xml"
    prefix:   /admin
admin_menu:
    resource: "@BoabCmsBundle/Resources/config/routing/menu.xml"

content_api:
    resource: "@BoabCmsBundle/Resources/config/routing/api.xml"
    prefix:   /{_api}
    requirements:
        _api: api|rest    
_mail_app:
    resource: "@MailerBundle/Resources/config/routes.xml"
