app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_user:
    resource: "@UserBundle/Resources/config/api/routes.xml"
    prefix:   /{_api}
    requirements:
        _api: api|rest

user_admin:
    resource: "@UserBundle/Resources/config/routing/admin.xml"
user_account:
    resource: "@UserBundle/Resources/config/routing/account.xml"

_content:
    resource: "@BoabCmsBundle/Resources/config/routing/content.xml"

_api_content:
    resource: "@BoabCmsBundle/Resources/config/routing/api_routes.xml"
    prefix:   /{_api}
    requirements:
        _api: api|rest    

_menu:
    resource: "@BoabCmsBundle/Resources/config/routing/menu.xml"

_cronjob:
    resource: "@CronBundle/Resources/config/routing/routes.xml"

_mail_app:
    resource: "@MailerBundle/Resources/config/routes.xml"
